name: 'GoReleaser'

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  goreleaser:
    name: 'Publish to release'
    strategy:
      matrix:
        project-path: ['./cmd/go-tts', './cmd/go-playback']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f $GITHUB_WORKSPACE/.goreleaser.yaml
          workdir: ${{ matrix.project-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
